baseURL = 'https://blog.virtual0ptr.top/'
title = 'Virtual0PTR Blog'
theme = 'ananke'
defaultContentLanguage = 'zh'
featured_image = '/images/background.jpg'
[params]
    commentoEnable = true
    custom_css = ["custom.css"]
[security]
    enableInlineShortcodes = false
    [security.exec]
      allow = [
        '^(dart-)?sass(-embedded)?$', 
        '^go$', 
        '^git$', 
        '^npx$', 
        '^postcss$', 
        '^tailwindcss$',
        '^vim$'
      ]
      osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']
[languages]
    [languages.en]
        contentDir = 'content/en'
        languageName = 'English'
        weight = 10
        [languages.en.menu]
            [[languages.en.menu.main]]
                name = 'Home'
                pageRef = '/'
                weight = 10
            [[languages.en.menu.main]]
                name = 'Tags'
                pageRef = '/tags'
                weight = 12
            [[languages.en.menu.main]]
                name = 'Archives'
                pageRef = '/archives'
                weight = 15
            [[languages.en.menu.main]]
                name = 'DN42'
                pageRef = '/tags/dn42'
                weight = 20
    [languages.zh]
        contentDir = 'content/zh'
        languageName = '简体中文'
        weight = 20
        [languages.zh.menu]
            [[languages.zh.menu.main]]
                name = '主页'
                pageRef = '/'
                weight = 10
            [[languages.zh.menu.main]]
                name = '标签'
                pageRef = '/tags'
                weight = 12
            [[languages.zh.menu.main]]
                name = '归档'
                pageRef = '/archives'
                weight = 15
            [[languages.zh.menu.main]]
                name = '关于'
                pageRef = '/about'
                weight = 16
            [[languages.zh.menu.main]]
                name = 'DN42'
                pageRef = '/tags/dn42'
                weight = 20


