baseURL = 'https://blog.0xptr.top/'
title = 'Virtual0PTR Blog'
theme = 'ananke'
defaultContentLanguage = 'zh'
featured_image = '/images/background.jpg'
[params]
    commentoEnable = true
[languages]
    [languages.en]
        contentDir = 'content/en'
        languageName = 'English'
        weight = 10
        [languages.en.menu]
            [[languages.en.menu.main]]
                name = 'Home'
                pageRef = '/'
                weight = 10
            [[languages.en.menu.main]]
                name = 'DN42'
                pageRef = '/about/dn42'
                weight = 20
    [languages.zh]
        contentDir = 'content/zh'
        languageName = '简体中文'
        weight = 20
        [languages.zh.menu]
            [[languages.zh.menu.main]]
                name = '主页'
                pageRef = '/'
                weight = 10
            [[languages.zh.menu.main]]
                name = 'DN42'
                pageRef = '/about/dn42'
                weight = 20


